#!/usr/bin/env bash
#脚本出现异常会立即退出
set -euo pipefail

# 根目录
ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

# 自动 export 配置块里的赋值，避免“脚本里配了但子进程收不到”。
set -a

# 如果存在网络相关环境配置，则加载
if [[ -f "${ROOT_DIR}/config/network.env" ]]; then
  # shellcheck disable=SC1091
  source "${ROOT_DIR}/config/network.env"
fi

# 生产侧默认配置集中放在 start.sh 里；如需覆盖，直接在调用前 export 同名环境变量。

# --- Common ---
LOG_LEVEL="${LOG_LEVEL:-WARN}"
LOG_STATUS_INTERVAL_SEC="${LOG_STATUS_INTERVAL_SEC:-0}"
EXT_TIMEOUT_SEC="${EXT_TIMEOUT_SEC:-300}"
PURGE_MQ_ON_START="${PURGE_MQ_ON_START:-1}"
TS_MAX_SKEW_SEC="${TS_MAX_SKEW_SEC:-100000000}"
DEBUG_INCLUDE_PATH_RESULT="${DEBUG_INCLUDE_PATH_RESULT:-0}"
MAP_CACHE_FILE="${MAP_CACHE_FILE:-}"

# --- Path Planning ---
SKIP_STATIC_TABLE="${SKIP_STATIC_TABLE:-1}"
PLANNER_STATIC_TABLE="${PLANNER_STATIC_TABLE:-${ROOT_DIR}/config/south_20260107_all.bin}"
PLANNER_TURN_PENALTY_MM="${PLANNER_TURN_PENALTY_MM:-3000}"
PLANNER_TURN_PENALTY_RETRY_RATIO="${PLANNER_TURN_PENALTY_RETRY_RATIO:-0.3333333333}"
PLANNER_TURN_PENALTY_LAST_RESORT_MM="${PLANNER_TURN_PENALTY_LAST_RESORT_MM:-0}"
OBSTACLE_BLOCK_NODE_MM="${OBSTACLE_BLOCK_NODE_MM:-300}"
OBSTACLE_BLOCK_EDGE_MM="${OBSTACLE_BLOCK_EDGE_MM:-300}"
CORRIDOR_MIN_LENGTH="${CORRIDOR_MIN_LENGTH:-3}"
CONGESTION_REGION_BRIDGE_MIN_NODES="${CONGESTION_REGION_BRIDGE_MIN_NODES:-4}"
CONGESTION_REGION_COUNT="${CONGESTION_REGION_COUNT:-0}"
CONGESTION_REGION_WINDOW="${CONGESTION_REGION_WINDOW:-2}"
CONGESTION_REGION_BIG_WINDOW="${CONGESTION_REGION_BIG_WINDOW:-2}"
CONGESTION_REGION_HARD_BLOCK="${CONGESTION_REGION_HARD_BLOCK:-1}"

# --- Reservation / Replan / Traffic ---
TRAIL_MAX_POINTS="${TRAIL_MAX_POINTS:-6}"
RESERVE_TTL_MS="${RESERVE_TTL_MS:-15000}"
RESERVE_COMMITTED_TTL_MS="${RESERVE_COMMITTED_TTL_MS:-15000}"
STATUS_STALE_RELEASE_MS="${STATUS_STALE_RELEASE_MS:-60000}"
USE_STATUS_NEXT_NODE="${USE_STATUS_NEXT_NODE:-0}"
STATUS_IDLE_RELEASE_ENABLE="${STATUS_IDLE_RELEASE_ENABLE:-0}"
STATUS_STATIC_SPEED_EPS="${STATUS_STATIC_SPEED_EPS:-20}"
STATUS_STATIC_RELEASE_MS="${STATUS_STATIC_RELEASE_MS:--1}"
TRAFFIC_PATH_PUBLISH_INTERVAL_MS="${TRAFFIC_PATH_PUBLISH_INTERVAL_MS:-1000}"
TRAFFIC_PATH_SEND_GROWING="${TRAFFIC_PATH_SEND_GROWING:-0}"
REPLAN_TICK_MS="${REPLAN_TICK_MS:-200}"
REPLAN_INTERVAL_MS="${REPLAN_INTERVAL_MS:-1000}"
REPLAN_INTERVAL_MIN_MS="${REPLAN_INTERVAL_MIN_MS:-500}"
REPLAN_INTERVAL_MAX_MS="${REPLAN_INTERVAL_MAX_MS:-1500}"
REPLAN_NEAR_GOAL_CHECK="${REPLAN_NEAR_GOAL_CHECK:-0}"
REPLAN_NEAR_GOAL_MM="${REPLAN_NEAR_GOAL_MM:-10000}"
REPLAN_SOFT_TIME_WINDOW_ENABLE="${REPLAN_SOFT_TIME_WINDOW_ENABLE:-0}"
REPLAN_MAJOR_STUCK_MS="${REPLAN_MAJOR_STUCK_MS:-2000}"
REPLAN_SUPER_AFTER_MAJOR_FAILS="${REPLAN_SUPER_AFTER_MAJOR_FAILS:-10}"
FAST_NEIGHBORHOOD_M="${FAST_NEIGHBORHOOD_M:-3.0}"
FAST_MAX_DETOUR_RATIO="${FAST_MAX_DETOUR_RATIO:-1.8}"
TRAFFIC_PATH_LINE_LOG_ENABLE="${TRAFFIC_PATH_LINE_LOG_ENABLE:-0}"

# --- Deadlock / Yield ---
DEADLOCK_DETECTION_ENABLE="${DEADLOCK_DETECTION_ENABLE:-1}"
DEADLOCK_DETECT_MS="${DEADLOCK_DETECT_MS:-2000}"
DEADLOCK_EDGE_STALE_MS="${DEADLOCK_EDGE_STALE_MS:-5000}"
DEADLOCK_SPEED_EPS_MM_S="${DEADLOCK_SPEED_EPS_MM_S:-1.0}"
DEADLOCK_YIELD_MS="${DEADLOCK_YIELD_MS:-3000}"
DEADLOCK_YIELD_MAX_MS="${DEADLOCK_YIELD_MAX_MS:-15000}"
DEADLOCK_HISTORY_WINDOW_MS="${DEADLOCK_HISTORY_WINDOW_MS:-30000}"
DEADLOCK_STALL_MULTIPLIER="${DEADLOCK_STALL_MULTIPLIER:-5}"

# --- Task Allocation ---
ALLOC_TASK_AGE_THRESHOLD_SEC="${ALLOC_TASK_AGE_THRESHOLD_SEC:-300}"
ALLOC_TASK_AGE_BONUS_MS_PER_SEC="${ALLOC_TASK_AGE_BONUS_MS_PER_SEC:-100}"
ALLOC_TASK_AGE_BONUS_MAX_MS="${ALLOC_TASK_AGE_BONUS_MAX_MS:-120000}"
ALLOC_TASK_AGE_MIN_COST_MS="${ALLOC_TASK_AGE_MIN_COST_MS:--60000}"
ALLOC_CONGESTION_PENALTY_RATIO="${ALLOC_CONGESTION_PENALTY_RATIO:-1.2}"
ALLOC_WAIT_PENALTY_COEFF="${ALLOC_WAIT_PENALTY_COEFF:-0.5}"
ALLOC_TOPK_RATIO="${ALLOC_TOPK_RATIO:-0.8}"
ALLOC_MAX_BATCH_SIZE="${ALLOC_MAX_BATCH_SIZE:-200}"

# --- Logging / Debug Artifacts ---
DEBUG_DIR="${DEBUG_DIR:-${ROOT_DIR}/debug}"
RECEIVER_LOG_KEEP="${RECEIVER_LOG_KEEP:-288}"
RECEIVER_LOG_ROTATE_SEC="${RECEIVER_LOG_ROTATE_SEC:-300}"
RECEIVER_LOG_PREFIX="${RECEIVER_LOG_PREFIX:-external_receiver}"
ROTATE_SCRIPT="${ROTATE_SCRIPT:-${ROOT_DIR}/script/rotating_tee.sh}"
RESULT_DUMP_KEEP_MAX="${RESULT_DUMP_KEEP_MAX:-200}"
RESULT_DUMP_DIR="${RESULT_DUMP_DIR:-}"
TRAFFIC_DUMP_KEEP_MAX="${TRAFFIC_DUMP_KEEP_MAX:-200}"

set +a

# Receiver log switches (default OFF; use START_DEBUG=1 to enable summaries).
START_DEBUG="${START_DEBUG:-0}"
if [[ "${START_DEBUG}" == "1" ]]; then
  export RECEIVER_LOG_ROUTE_SUMMARY="${RECEIVER_LOG_ROUTE_SUMMARY:-1}"
  export RECEIVER_LOG_ROUTE_DETAIL="${RECEIVER_LOG_ROUTE_DETAIL:-0}"
  export RECEIVER_LOG_STATUS_SUMMARY="${RECEIVER_LOG_STATUS_SUMMARY:-1}"
  export RECEIVER_LOG_STARTUP_SUMMARY="${RECEIVER_LOG_STARTUP_SUMMARY:-1}"
  export RECEIVER_LOG_STATUS_NODE_XY="${RECEIVER_LOG_STATUS_NODE_XY:-0}"
  export RECEIVER_LOG_STATUS_SNAPSHOT="${RECEIVER_LOG_STATUS_SNAPSHOT:-0}"
  export RECEIVER_LOG_TRAIL_POINTS="${RECEIVER_LOG_TRAIL_POINTS:-0}"
  export RECEIVER_LOG_EACH_MESSAGE="${RECEIVER_LOG_EACH_MESSAGE:-0}"
  export RECEIVER_LOG_EACH_MESSAGE_STATUS="${RECEIVER_LOG_EACH_MESSAGE_STATUS:-0}"
  export RECEIVER_LOG_TRAFFIC_SUMMARY="${RECEIVER_LOG_TRAFFIC_SUMMARY:-1}"
  export RECEIVER_LOG_TRAFFIC_JSON="${RECEIVER_LOG_TRAFFIC_JSON:-0}"
  export RECEIVER_LOG_TRAFFIC_DETAIL="${RECEIVER_LOG_TRAFFIC_DETAIL:-0}"
  export RECEIVER_LOG_ALLOC_SUMMARY="${RECEIVER_LOG_ALLOC_SUMMARY:-0}"
  export RECEIVER_LOG_ALLOC_PROFILE="${RECEIVER_LOG_ALLOC_PROFILE:-0}"
  export RECEIVER_LOG_ALLOC_RESULT="${RECEIVER_LOG_ALLOC_RESULT:-0}"
  export RECEIVER_LOG_ALLOC_DETAIL="${RECEIVER_LOG_ALLOC_DETAIL:-0}"
  export RECEIVER_LOG_ALLOC_DIAG="${RECEIVER_LOG_ALLOC_DIAG:-0}"
  export RECEIVER_LOG_SCHED_REQUEST="${RECEIVER_LOG_SCHED_REQUEST:-1}"
  export RECEIVER_LOG_SCHED_TASK_DETAIL="${RECEIVER_LOG_SCHED_TASK_DETAIL:-0}"
  export RECEIVER_LOG_REJECT_RESP="${RECEIVER_LOG_REJECT_RESP:-0}"
  export RECEIVER_LOG_ROUTE_WARN="${RECEIVER_LOG_ROUTE_WARN:-0}"
else
  # 强制静音：覆盖外部 shell 里可能残留的 export 值。
  export RECEIVER_LOG_ROUTE_SUMMARY="0"
  export RECEIVER_LOG_ROUTE_DETAIL="0"
  export RECEIVER_LOG_STATUS_SUMMARY="0"
  export RECEIVER_LOG_STARTUP_SUMMARY="0"
  export RECEIVER_LOG_STATUS_NODE_XY="0"
  export RECEIVER_LOG_STATUS_SNAPSHOT="0"
  export RECEIVER_LOG_TRAIL_POINTS="0"
  export RECEIVER_LOG_EACH_MESSAGE="0"
  export RECEIVER_LOG_EACH_MESSAGE_STATUS="0"
  export RECEIVER_LOG_TRAFFIC_SUMMARY="0"
  export RECEIVER_LOG_TRAFFIC_JSON="0"
  export RECEIVER_LOG_TRAFFIC_DETAIL="0"
  export RECEIVER_LOG_ALLOC_SUMMARY="0"
  export RECEIVER_LOG_ALLOC_PROFILE="0"
  export RECEIVER_LOG_ALLOC_RESULT="0"
  export RECEIVER_LOG_ALLOC_DETAIL="0"
  export RECEIVER_LOG_ALLOC_DIAG="0"
  export RECEIVER_LOG_SCHED_REQUEST="0"
  export RECEIVER_LOG_SCHED_TASK_DETAIL="0"
  export RECEIVER_LOG_REJECT_RESP="0"
  export RECEIVER_LOG_ROUTE_WARN="0"
fi

# 其他高频日志默认关闭。
export STATUS_LAG_LOG_SEC="${STATUS_LAG_LOG_SEC:-0}"
export STATUS_LAG_WARN_MS="${STATUS_LAG_WARN_MS:-0}"
export REPLAN_PROFILE="${REPLAN_PROFILE:-0}"
export EXT_PRINT_UNALLOC_CAUSE="${EXT_PRINT_UNALLOC_CAUSE:-0}"

if [[ "${DEBUG_DIR}" != /* ]]; then
  DEBUG_DIR="${ROOT_DIR}/${DEBUG_DIR}"
fi
mkdir -p "${DEBUG_DIR}"

TS="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${DEBUG_DIR}/${RECEIVER_LOG_PREFIX}_${TS}.log"
ln -sf "${LOG_FILE}" "${DEBUG_DIR}/external_receiver_latest.log" 2>/dev/null || true

if [[ -z "${MAP_CACHE_FILE:-}" ]]; then
  MAP_CACHE_FILE="${DEBUG_DIR}/received_map.json"
fi

export DEBUG_DIR
export RESULT_DUMP_DIR
export TRAFFIC_DUMP_KEEP_MAX
export MAP_CACHE_FILE

# 可用时优先使用可执行的编译产物目录
RECEIVER_BIN="${ROOT_DIR}/build/bin/external_receiver"
if [[ ! -x "${RECEIVER_BIN}" && -x "${ROOT_DIR}/build_local/bin/external_receiver" ]]; then
  RECEIVER_BIN="${ROOT_DIR}/build_local/bin/external_receiver"
fi
chmod +x "${RECEIVER_BIN}"

# 启动 external_receiver（按时间滚动日志，避免单文件过大）
if [[ "${RECEIVER_LOG_ROTATE_SEC}" =~ ^[0-9]+$ ]] && (( RECEIVER_LOG_ROTATE_SEC > 0 )); then
  exec > >(
    bash "${ROTATE_SCRIPT}" \
      --log-dir "${DEBUG_DIR}" \
      --prefix "${RECEIVER_LOG_PREFIX}" \
      --first-file "${LOG_FILE}" \
      --rotate-sec "${RECEIVER_LOG_ROTATE_SEC}" \
      --keep "${RECEIVER_LOG_KEEP}" \
      --prune-json \
      --json-dir "${RESULT_DUMP_DIR}" \
      --latest-symlink "${DEBUG_DIR}/external_receiver_latest.log"
  ) 2>&1
else
  exec > >(tee -a "${LOG_FILE}") 2>&1
fi

exec "${RECEIVER_BIN}"
